### ISSUE TITLE
Error in interactive.py

### ISSUE THREAD

**Issue by Light542** [zwhe99/MAPS-mt#2]
I am using interactive.py and done preparation as told. Getting below error:
ImportError: cannot import name 'demo_ex_dict' from 'data' (unknown location)

I don't know what is this data package, not able to find it in the repo. Please help.

Thanks in advance.

**Comment by zwhe99** [comment]
Hi @Light542. It seems weird because I was unable to replicate the issue you're experiencing. Have you considered re-cloning the repository to ensure all the folders are complete?

'data' package is here: https://github.com/zwhe99/MAPS-mt/tree/main/data

Please let me know if the problem persists.

**Comment by Light542** [comment]
Thank you for the response. After cloning again, the issue is resolved

**Comment by zwhe99** [comment]
Nice! Closed this issue.
