### ISSUE TITLE
illegal hardware instruction ?

### ISSUE THREAD

**Issue by Hongbin-Ze** [zwhe99/MAPS-mt#4]
I have a problem with "interactive.py" and when I run it as instructed, I get the error: "zsh: illegal hardware instruction python3 interactive.py "

After checking, I found that the error came from: "from comet import load_from_checkpoint, download_model", but after reinstalling the comet library, the problem still exists.

Please help. Thanks in advance.

**Comment by zwhe99** [comment]
Are you using MacBook pro M1?

**Comment by Hongbin-Ze** [comment]
Yes

**Comment by zwhe99** [comment]
I guess your conda is not compatible with M1. Maybe you should reinstall it from https://www.anaconda.com/download. Note that select the version that is compatible with M1.

**Comment by Hongbin-Ze** [comment]
Thanks a lot, the problem is solved!

**Comment by zwhe99** [comment]
Good!

**Comment by Hongbin-Ze** [comment]
On another note, how much did the api calls cost for the whole project?

**Comment by zwhe99** [comment]
I don't have a specific number, but it's about a few hundred dollars.
