### ISSUE TITLE
Trailing comma after `TOPICS`

### ISSUE THREAD

**Issue by j-luo93** [zwhe99/MAPS-mt#7]
I noticed that there was a trailing comma after `TOPICS` in [`format_ask_topic.py`](https://github.com/zwhe99/MAPS-mt/blob/main/data/format_ask_topic.py#L13). This will make `TOPICS` a single-item tuple consisting of a five-item list. As a result, the prompts for asking topics will be a (wrong) 1-shot example with mismatched topic keywords, instead of 5-shot.

**Comment by zwhe99** [comment]
Just fixed it! Thanks for pointing this out!
